[[project]]
name = "Rye"
desc = "Open Source Virtual Coworking Space"
links = [
        { name = "About", url = "" },
        { name = "IOS", url = "" },
        { name = "Android", url = "" },
]

[[project]]
name = "Iyagi"
desc = "Open Source Web Novel Platform"
links = [{ name = "About", url = "" }]

[[project]]
name = "Goyo"
desc = "Open Source Mindfulness Meditation App"
links = [{ name = "About", url = "" }]
