[[project]]
name = "Gaji"
desc = "Task Manager App"
links = [
        { name = "About", url = "https://github.com/krapjost/gaji" },
        { name = "IOS", url = "" },
        { name = "Android", url = "" },
]

[[project]]
name = "Iyagi"
desc = "Web Novel Platform"
links = [{ name = "About", url = "" }]

[[project]]
name = "Goyo"
desc = "Mindfulness Meditation App"
links = [{ name = "About", url = "" }]
