baseURL = 'http://krapjost.github.io'
theme = 'hugo-book'
defaultContentLang = 'en'
[markup.goldmark.renderer]
  unsafe = true
[menu]
[[menu.after]]
  name = "Github"
  url = "https://github.com/krapjost"

[params]
  BookTheme = 'dark'
  BookRepo = 'https://github.com/krapjost/docs'
  BookSearch = true

[languages]
[languages.ko]
  title = '정원'
  languageName = '한국어'
  contentDir = 'content_ko'
  weight = 1
[languages.en]
  title = 'Garden'
  languageName = 'English'
  contentDir = 'content'
  weight = 2
